"""FOLD-FREENESS sweep: discharge the Lean face theorem's `hfold` for a
concrete teacher rectangle, as a replayable interval certificate.

WHAT IS BEING CERTIFIED, and what it is NOT.  The Lean theorem
`censusAngleMapJ_familyCount_eq_witness_on_censusBox` carries fold-freeness as
an EXPLICIT hypothesis.  This sweep discharges that hypothesis for the CONCRETE
census map on the named rectangle -- never as a general theorem, per the
owner's scope rule.  The count that results rests on a Lean implication plus
this replayable computation, and the two halves stay visibly separate.

THE OBLIGATION, in the form that is swept.  `hfold` says: for every teacher
`p` in the rectangle and every `x` in the student domain, if the census angle
map vanishes at `(p, x)` then the Jacobian determinant is nonzero there.  Its
contrapositive is an EXCLUSION statement -- there is no `(p, x)` at which the
angle map vanishes AND the mass-free type-boundary function vanishes -- so
each box is discharged by ONE of two one-sided tests, and nothing here
encloses a moving solution or contracts onto one:

  SCHUR  the mean-value enclosure of `generalJKernelTeacherSchurDetT` misses
         zero on the box.  It depends on `(beta, th0, th1)` only, so ONE
         verdict serves every `y` in the rectangle.
  MAP    some component of the angle map has an enclosure missing zero over
         the whole `y`-range, so the map cannot vanish anywhere in the box.
  FIT    the box lies ENTIRELY inside the tube around the exact-fit arc
         `s = 0 (mod 2pi), D = beta`, where the mass-free function is
         identically zero by a theorem of the tree
         (`generalJAngleEq_eq_zero_at_exactFit` makes the substituted kernel
         vector `(0,0)`).  That arc is covered by the schema's OTHER certified
         route, the mass-carrying `det T != 0`, which the census certifies
         through its interval Schur type.  A box that merely MEETS the tube is
         NOT skipped -- only one contained in it.

FORMAT.  The same replayable bisection tree as the census certificates: the
root box comes from the spec and is regenerated by the checker, the split rule
is deterministic (bisect the widest side, child 0 = lower half), the tree is
walked in preorder, `1` = internal and `0` = leaf followed by two verdict bits
(SCHUR 0, MAP 1, FIT 2, UNDECIDED 3).  An undecided leaf fails the replay.

Usage: `python3 foldfree_sweep.py <b0> <b1> <y0> <y1> <tag> [fitr] [budget]`
"""
import base64
import json
import os
import sys
import time

import mpmath

import census_cert as X
import face_bb_signlaw as F
import noncentered as J
import kernel_schur_mv as MV

HERE = os.path.dirname(os.path.abspath(__file__))
CODE = {"SCHUR": 0, "MAP": 1, "FIT": 2, "UNDECIDED": 3}
NAME = {v: k for k, v in CODE.items()}


def mk(lo, hi):
    return X.iv.mpf([mpmath.mpf(repr(lo)), mpmath.mpf(repr(hi))])


def root_box(spec):
    """The whole region, regenerated from the spec ALONE.

    FOUR-DIMENSIONAL: `(beta, y, s, D)`.  The first version swept only
    `(beta, s, D)` with `y` entering as a FIXED interval, which put a floor
    under the angle-map test that no amount of `(beta, s, D)` subdivision
    could beat -- measured at the collar corner, the residual's relative
    enclosure width is 127 at a `y`-width of 2e-3 and 1.5 at 2e-5, where the
    test fires.  The obligation is 4-D and so is the sweep.  (The determinant
    test remains `y`-FREE, which is a genuine advantage rather than an
    accident: one SCHUR verdict still serves every `y` in the box.)"""
    two_pi = float(J.hi(2 * X.PIv))
    dpi = float(J.hi(X.PIv))
    return (spec["b0"], spec["b1"], spec["y0"], spec["y1"],
            spec["seam"], spec["seam"] + two_pi,
            spec["delta"], dpi + spec["dmax_pad"])


def root_cells(spec):
    """The PARTITION into root cells, regenerated from the spec ALONE.

    The region is cut into `n_parts` equal slices along the `s`-axis (the
    longest side, one full period).  The partition is part of the spec so the
    checker rebuilds exactly the same cells and can verify that their union is
    the region: consecutive cells share an endpoint and the two ends match the
    region's, so coverage stays STRUCTURAL rather than asserted -- the same
    property the point certificates rely on.  Parallel workers take disjoint
    index ranges of this list and their subtrees are concatenated in index
    order; a face is complete only if every subtree is complete AND the
    partition covers.
    """
    bl, bh, yl, yh, sl, sh, dl, dh = root_box(spec)
    n = spec["n_parts"]
    cells = []
    for i in range(n):
        a = sl + (sh - sl) * i / n
        b = sl + (sh - sl) * (i + 1) / n
        cells.append((bl, bh, yl, yh, a, b, dl, dh))
    return cells


def partition_covers(spec):
    """Does the regenerated partition tile the region exactly?"""
    bl, bh, yl, yh, sl, sh, dl, dh = root_box(spec)
    cells = root_cells(spec)
    if not cells:
        return False
    if cells[0][4] != sl or cells[-1][5] != sh:
        return False
    for i in range(len(cells) - 1):
        if cells[i][5] != cells[i + 1][4]:
            return False
        if cells[i][:4] != (bl, bh, yl, yh) or cells[i][6:] != (dl, dh):
            return False
    return True


def inside_fit_tube(spec, bl, bh, yl, yh, sl, sh, dl, dh):
    two_pi = float(J.hi(2 * X.PIv))
    r = spec["fitr"]
    return (sl >= two_pi - r and sh <= two_pi + r
            and dl >= spec["b0"] - r and dh <= spec["b1"] + r)


def verdict(spec, bl, bh, yl, yh, sl, sh, dl, dh):
    if inside_fit_tube(spec, bl, bh, yl, yh, sl, sh, dl, dh):
        return "FIT"
    B = mk(bl, bh)
    T1 = mk(sl, sh)
    Dm = mk(dl, dh)
    # ORDER IS BY COST, NOT BY PREFERENCE.  Either verdict discharges the box,
    # so the cheap test goes first: measured 10.1 ms for MAP against 37.1 ms
    # for the mean-value SCHUR test, and at coarse scales MAP kills almost
    # everything (2843 against 0 in the first probe).  Trying SCHUR first made
    # every box pay the expensive test.  The checker calls THIS function, so
    # its ordering and the sweep's agree by construction.
    try:
        Y = mk(yl, yh)
        s0, s1 = X.masses_at(Y)
        Tc = X.Teacher(B, s0, s1)
        # TWO admissible enclosures of the same residual, cheap one first.
        # The plain row form costs ~10 ms; the MEAN-VALUE row form costs more
        # but kills far more, and the gain is largest exactly where it matters
        # for a bisection sweep -- on COARSE boxes, where killing one removes
        # its whole subtree.  Measured on this cell: at side 3e-2 the plain
        # form kills 82 of 120 and the mean-value form 110 of 120, dropping the
        # survivor fraction from 32 % to 8 %.  Either firing discharges the
        # box, so trying both is sound and the checker calls this same
        # function.
        E0, E1 = X.sep_res_rowform(Tc, T1 + Dm, T1, None, Dm=Dm)
        if X.sgn(E0) != 0 or X.sgn(E1) != 0:
            return "MAP"
        if any(F.rowform_centered_sign(Tc, T1, Dm, None)):
            return "MAP"
    except Exception:
        pass
    try:
        mv = MV.detT_meanvalue(B, mpmath.mpf(repr(sl)), mpmath.mpf(repr(sh)),
                               mpmath.mpf(repr(dl)), mpmath.mpf(repr(dh)))
        if X.sgn(mv) != 0:
            return "SCHUR"
    except Exception:
        pass
    return None


def child(bx, bit):
    """Deterministic split of the FOUR-dimensional box: widest side, child 0
    the lower half.  `y` is one of the four -- omitting it was the first
    version's design flaw."""
    w = (bx[1] - bx[0], bx[3] - bx[2], bx[5] - bx[4], bx[7] - bx[6])
    i = w.index(max(w))
    lo, hi = bx[2 * i], bx[2 * i + 1]
    m = (lo + hi) / 2
    out = list(bx)
    if bit == 0:
        out[2 * i + 1] = m
    else:
        out[2 * i] = m
    return tuple(out)


def main():
    b0, b1, y0, y1 = (float(sys.argv[i]) for i in (1, 2, 3, 4))
    tag = sys.argv[5]
    n_parts = int(sys.argv[6])
    lo_idx = int(sys.argv[7])
    hi_idx = int(sys.argv[8])          # cells [lo_idx, hi_idx)
    fitr = float(sys.argv[9]) if len(sys.argv) > 9 else 0.05
    budget = int(sys.argv[10]) if len(sys.argv) > 10 else 20000000
    spec = {"b0": b0, "b1": b1, "y0": y0, "y1": y1, "seam": 0.137,
            "delta": 0.02, "dmax_pad": 0.05, "fitr": fitr, "minw": 1e-8,
            "n_parts": n_parts, "order": "map_first"}
    if not partition_covers(spec):
        print("SPEC REJECTED: the partition does not tile the region")
        return 2
    cells = root_cells(spec)
    print("fold-freeness sweep  beta=[%g,%g] y=[%g,%g]  cells [%d,%d) of %d"
          % (b0, b1, y0, y1, lo_idx, hi_idx, n_parts), flush=True)
    bits = []
    counts = {k: 0 for k in CODE}
    t0 = time.time()
    n = 0

    def vol(bx):
        return ((bx[1] - bx[0]) * (bx[3] - bx[2])
                * (bx[5] - bx[4]) * (bx[7] - bx[6]))

    live = 0.0
    for ci in range(lo_idx, hi_idx):
        stack = [cells[ci]]
        while stack:
            bx = stack.pop()
            n += 1
            if n > budget:
                print("BUDGET EXHAUSTED at cell %d" % ci, flush=True)
                return 2
            v = verdict(spec, *bx)
            if v is None:
                w = max(bx[1] - bx[0], bx[3] - bx[2], bx[5] - bx[4],
                        bx[7] - bx[6])
                if w < spec["minw"]:
                    bits.append(0)
                    bits.extend((1, 1))          # UNDECIDED = 3
                    counts["UNDECIDED"] += 1
                    live += vol(bx)
                    continue
                bits.append(1)
                stack.append(child(bx, 1))
                stack.append(child(bx, 0))
                continue
            bits.append(0)
            bits.extend(((CODE[v] >> 1) & 1, CODE[v] & 1))
            counts[v] += 1
            if n % 2000 == 0:
                print("  cell %3d  nodes %8d  map %7d schur %6d fit %5d "
                      "undec %d  stack %5d  %.0fs"
                      % (ci, n, counts["MAP"], counts["SCHUR"], counts["FIT"],
                         counts["UNDECIDED"], len(stack), time.time() - t0),
                      flush=True)
    secs = time.time() - t0
    pad = (-len(bits)) % 8
    packed = bytearray()
    for i in range(0, len(bits) + pad, 8):
        byte = 0
        for k in range(8):
            byte = (byte << 1) | (bits[i + k] if i + k < len(bits) else 0)
        packed.append(byte)
    doc = {"spec": spec, "lo_idx": lo_idx, "hi_idx": hi_idx,
           "n_nodes": len(bits),
           "bits_b64": base64.b64encode(bytes(packed)).decode()}
    out = os.path.join(HERE, "foldfree_%s_p%03d.json" % (tag, lo_idx))
    with open(out, "w") as fh:
        json.dump(doc, fh, separators=(",", ":"))
    print("cells [%d,%d)  nodes %d  map %d schur %d fit %d undecided %d"
          % (lo_idx, hi_idx, n, counts["MAP"], counts["SCHUR"], counts["FIT"],
             counts["UNDECIDED"]))
    print("wall clock %.1f s ; %s (%.1f KB)"
          % (secs, os.path.basename(out), len(packed) / 1024.0))
    if counts["UNDECIDED"]:
        print("PART INCOMPLETE: %d undecided leaves (live volume %.3e)"
              % (counts["UNDECIDED"], live))
        return 1
    print("PART COMPLETE")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
